server:
  port: 9090
spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/javaappd
    username: postgres
    password: 123ali12312
    driver-class-name: org.postgresql.Driver
    data: classpath:data.sql
  jpa:
    properties:
      hibarnate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: cybertekschool.email@gmail.com
    password: Cybertekschool@2020
  sql:
    init:
#      mode: always
security:
      jwt:
        secret-key: javaapp
springdoc:
  swagger-ui:
    path: /swagger-ui.html